# Generated by Django 2.2.7 on 2019-11-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.IntegerField()),
                ('comp_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('tel', models.IntegerField(max_length=8)),
            ],
        ),
    ]
